Linaro/vixl

- src/aarch64/logic-aarch64.cc
Clang warns (and errors due to -Werror) about these comparisons
losing precision as a result of the constants kXMaxInt and kXMaxUInt
being unrepresentable as a double. Although the warning could be
silenced by explicitly casting the constants to doubles, this relies
on implementation-defined rounding behavior so just write out the
floating point literals explicitly.
> Fix clang build.

- examples/aarch64/custom-disassembler.cc
- examples/aarch64/non-const-visitor.cc
Disable linter for calls to regex_match, as this causes failures for the version
of clang-tidy used in the Mac CI.
> Disable linter on regex calls

- src/aarch64/assembler-aarch64.h
Prevents a stray variable shadowing warning from appearing in projects including vixl with -Wshadow enabled.
`operands-aarch64.h` defines a bunch of vector register convenience operands via the `DEFINE_VREGISTERS` preprocessor define, which results in the `b5` convenience operand being shadowed by the local `b5` variable.
> assembler-aarch64: Prevent -Wshadow warning

- src/aarch64/assembler-aarch64.cc
Clang 14 (current trunk) warns about the use of a bitwise operation on booleans.
> Fix bitwise-instead-of-logical warning in assembler-aarch64.cc

- src/aarch32/instructions-aarch32.h
Fixes compilation on Debian armel, see https://buildd.debian.org/status/fetch.php?pkg=vixl&arch=armel&ver=5.1.0-1&stamp=1637517716&raw=0
Previously, Vixl would force hard float on all arm CPUs, by checking only for `__arm__`. This would cause GCC to throw an internal error when compiling with `-mfloat-abi=soft`. See also this example on Compiler Explorer: https://compiler-explorer.com/z/zsn5vaMna
> fix: do not force HARDFLOAT when using soft fp

- doc/aarch64/supported-instructions-aarch64.md
- tools/make_instruction_doc_aarch64.pl
The Markdown to HTML generator Github uses appears to want a newline after HTML
in order to recognise Markdown tags. Fix the document and generator to do this.
> Fix section header in supported instructions document

- src/aarch64/cpu-aarch64.cc
- src/aarch64/cpu-aarch64.h
- src/cpu-features.h
Allows querying for the existence of FEAT_AFP (alternate floating-point behavior).
While we're in the same area, we can also fill in detection for the existing MTE feature bits
> aarch64: Allow testing for the presence of FEAT_AFP

- src/aarch64/cpu-aarch64.cc
- src/aarch64/cpu-aarch64.h
- src/cpu-features.h
Fills out the remaining unimplemented handling of defined hwcap bits by allowing checking for FEAT_ECV (Enhanced Counter Virtualization), and FEAT_RPRES (Extended precision for Reciprocal Square Root Estimate and Reciprocal Estimate).
Now all currently defined hwcap bits are handled
> aarch64: Allow testing for the presence of FEAT_ECV and FEAT_RPRES

- src/aarch64/cpu-aarch64.cc
- src/aarch64/cpu-aarch64.h
- src/aarch64/instructions-aarch64.h
- src/aarch64/logic-aarch64.cc
- src/aarch64/simulator-aarch64.cc
- src/aarch64/simulator-aarch64.h
- src/aarch64/simulator-constants-aarch64.h
- test/aarch64/test-assembler-aarch64.h
- test/aarch64/test-metadata-aarch64.cc
- test/aarch64/test-simulator-aarch64.cc
MTE is the first-supported target. Add an example to demonstrate how it works.
> A prototype to support memory metadata in the Simulator.

- src/aarch32/disasm-aarch32.cc
- src/aarch32/disasm-aarch32.h
- src/aarch32/instructions-aarch32.cc
- src/aarch32/instructions-aarch32.h
- src/aarch32/macro-assembler-aarch32.cc
- src/aarch64/assembler-aarch64.cc
- src/aarch64/assembler-aarch64.h
- src/aarch64/assembler-sve-aarch64.cc
- src/aarch64/cpu-aarch64.cc
- src/aarch64/decoder-aarch64.cc
- src/aarch64/disasm-aarch64.cc
- src/aarch64/macro-assembler-aarch64.cc
- src/aarch64/operands-aarch64.cc
- src/aarch64/operands-aarch64.h
- src/assembler-base-vixl.h
- src/code-buffer-vixl.cc
- src/globals-vixl.h
- src/utils-vixl.cc
- src/utils-vixl.h
- test/aarch64/test-assembler-aarch64.cc
Also, fix almost all warnings with the "/W3" setting (default for new command-line projects), and some with "/W4" and "/Wall". The simulator implementation is out of scope because it uses too many POSIX interfaces to be usable (and in fact buildable) on Windows.
> Fix compilation with Microsoft Visual C++

- src/aarch64/logic-aarch64.cc
Fixes a case in the simulator where the upper lanes of the register will be cleared before the narrowing operation occurs.
Normally, clearing beforehand works... as long as your source and destination are always different. When the source and destination are the same this trounces data that the narrowing operation needs to use.
Now all the narrowing operations should work correctly if the source and destination are the same.
> logic-aarch64: Fix simulator register clearing bug in extractnarrow

- test/aarch64/test-assembler-neon-aarch64.cc
Add a simple regression test for xtn and related instructions. The test fails for revisions before 1ba324d89f7d3bf8471a2aa42d8c90a9b8aad341
> Regression test for XTN fix

- src/aarch64/instructions-aarch64.cc
The ARM architecture manual states that a destructive SVE EXT instructions might be preceded by a MOVPRFX instruction, and that this is allowed, but that:
1. The MOVPRFX instruction must be unpredicated
2. The MOVPRFX instruction must specify the same destination as the EXT instruction.
3. The destination register cannot refer to any other source operand in the EXT instruction.
This allows MOVPRFX to work with destructive variants of EXT instead of hitting an assertion in the simulator.
> instructions-aarch64: Handle destructive EXT in CanTakeSVEMovprfx

- src/aarch64/instructions-aarch64.cc
- test/aarch64/test-api-movprfx-aarch64.cc
Test the change in c40e2ab0d31b2460537ec10794cb34343da68606 and fix constructive splice similarly.
> Add regression test for movprfx/ext and fix splice

- src/aarch64/cpu-aarch64.cc
- src/cpu-features.h
Allows testing the new hwcap for determining SVE support for extended BFloat16 behavior on Linux systems.
> aarch64: Allow testing for the presence of SVE FEAT_EBF16

- src/aarch64/logic-aarch64.cc
- src/aarch64/simulator-aarch64.cc
In a few SVE load stores, register 31 should be the stack pointer rather than the zero register
> simulator-aarch64: Fix use of zero register in several SVE load/stores

- src/aarch64/decoder-visitor-map-aarch64.h
- src/aarch64/disasm-aarch64.cc
- 22ad42d9ff1fe30c865e8b6de2f4ea36b699d221 removes references to the no longer used `msr_si_pstate` instruction.
- e774feff850f1837603009f08900880ae353c565 removes extra `_` characters in some instruction names.
> Fix incorrect instruction mappings

- test/aarch64/test-assembler-aarch64.cc
In particular, the test changed the rounding mode, which caused another test to fail when run on AArch64 hardware with --run-all.
> Restore FPCR after modifying it in a test.

- src/aarch64/simulator-aarch64.cc
- test/aarch64/test-assembler-aarch64.cc
Pointer authentication instructions allow the stack pointer as source for the modifier, but simulation was using the zero register instead. Fix this and add a regression test.
> Fix pointer authentication modifier source register

- examples/aarch64/morello-wx.cc
- src/code-buffer-vixl.cc
- test/aarch64/test-assembler-aarch64.cc
- test/aarch64/test-assembler-morello-aarch64.cc
- test/test-api.cc
`test-runner --run-all` now passes on Morello hybrid.
> Fix Morello hybrid tests.

- src/aarch64/registers-aarch64.cc
- src/aarch64/registers-aarch64.h
- test/aarch64/test-api-morello-aarch64.cc
Morello purecap porting will frequently need to derive an aliasing register with a given size, for example to match the host pointer size. This is quite a verbose operation in current VIXL, and is easy to get wrong. This patch adds a convenience helper.
> Add convenient size-conversions for CPURegister.

- examples/aarch64/swap-int32.cc
- src/aarch64/macro-assembler-aarch64.cc
- src/aarch64/macro-assembler-aarch64.h
- test/aarch64/test-assembler-aarch64.cc
- test/aarch64/test-assembler-morello-aarch64.cc
This is a prerequisite for purecap (AAPCS64-cap), which uses csp as a stack pointer. Unfortunately, this is a breaking change, since StackPointer() now needs to return a CPURegister.
The usual stack helpers (including the shadow stack mechanism) work with a capability stack pointer from C64 code. However, Push() and Pop() won't currently work if an "alt-base" addressing mode would be required, because Morello lacks alt-base pre- and post-index forms. Further work could relax this restriction, if required.
> Morello: Allow StackPointer() to be a capability.

- src/aarch64/macro-assembler-aarch64.h
- src/aarch64/macro-assembler-sve-aarch64.cc
- test/aarch64/test-assembler-sve-aarch64.cc
- test/aarch64/test-disasm-sve-aarch64.cc
Without this patch, the macro assembler freely rearranges the registers passed for the BIC instruction to ensure the first source register is the same as the destination register, which it does because the instruction is considered to be commutative. However, the bit-clear instruction is non-commutative as it is the second source register which is negated, and so these should not be simply re-arranged without additional logic.
Instead, define Bic to be non-commutative as part of VIXL_SVE_NONCOMM_ARITH_ZPZZ_LIST.
Modify the tests for SVE predicated bit-clears accordingly.
> Fix BIC macro assembler definition to be non-commutative

- doc/aarch64/topics/index.md
- doc/aarch64/topics/simulator-debugger.md
- examples/aarch64/debugging.cc
- src/aarch64/debugger-aarch64.cc
- src/aarch64/debugger-aarch64.h
- src/aarch64/simulator-aarch64.cc
- src/aarch64/simulator-aarch64.h
- test/aarch64/test-debugger-aarch64.cc
- test/aarch64/test-debugger-aarch64.h
Add a basic debugger to the VIXL simulator. Once enabled (by default the debugger is disabled) any brk instruction encountered while simulating will cause the interactive debugger to be launched.
The debugger supports the following features:
- Break
- Step
- Continue
- Printing registers
- Toggling tracing
- Switching to GDB
> Add a debugger to VIXL simulator

- src/aarch64/assembler-aarch64.cc
- src/aarch64/assembler-aarch64.h
- src/aarch64/cpu-features-auditor-aarch64.cc
- src/aarch64/cpu-features-auditor-aarch64.h
- src/aarch64/decoder-visitor-map-aarch64.h
- src/aarch64/disasm-aarch64.cc
- src/aarch64/disasm-aarch64.h
- src/aarch64/instructions-aarch64.cc
- src/aarch64/instructions-aarch64.h
- src/aarch64/logic-aarch64.cc
- src/aarch64/registers-aarch64.cc
- src/aarch64/registers-aarch64.h
- src/aarch64/simulator-aarch64.cc
- src/aarch64/simulator-aarch64.h
- test/aarch64/test-assembler-neon-aarch64.cc
- test/aarch64/test-cpu-features-aarch64.cc
- test/aarch64/test-disasm-neon-aarch64.cc
- test/aarch64/test-simulator-aarch64.cc
- test/aarch64/test-simulator-sve-aarch64.cc
Extend the Neon PMULL instruction to support 1Q destination registers when the CPU feature is supported.
Co-authored-by: Anton Kirilov <anton.kirilov@arm.com>
> Support PMULL for 1Q destination vectors

- src/aarch64/simulator-aarch64.cc
- test/aarch64/test-simulator-aarch64.cc
All memory read functions (e.g: ld1, ld2, etc...) return a value (either std::nullopt or false) to signal that the memory read failed. Some of these memory read functions were not being checked for failure; fix this by checking these functions for failure.
> Check ld* functions for failure

- src/aarch64/logic-aarch64.cc
- src/aarch64/simulator-aarch64.cc
- test/aarch64/test-assembler-sve-aarch64.cc
Fix some Neon lengthening, narrowing and insertion instructions that should zero the upper bits of SVE registers, and add regression tests.
In particular, this fixes ADDHN2, FCVTL, FCVTL2, FCVTN2, FCVTXN2, FMOV (to d[1]), LD1 (single element), RADDHN2, RSUBHN2, SQXTN2, SQXTUN2, SUBHN2, UQXTN2 and XTN2 for simulated systems with VL > 128 bits.
Also, enable FCMLA by-element instructions, for which code already exists but wasn't being called in simulation.
> Fix zeroing part of SVE register for Neon instructions

- src/aarch64/disasm-aarch64.cc
- test/aarch64/test-disasm-aarch64.cc
- test/aarch64/test-disasm-neon-aarch64.cc
Disassembling some FCM, RDM and dot product instructions could report vector types that are undefined for the associated mnemonics. Fix this and add tests.
> Fix disassembly of Neon FCM, RDM and dot product instructions

- src/aarch64/assembler-aarch64.cc
- src/aarch64/assembler-aarch64.h
- src/aarch64/cpu-features-auditor-aarch64.cc
- src/aarch64/disasm-aarch64.cc
- src/aarch64/logic-aarch64.cc
- src/aarch64/macro-assembler-aarch64.h
- src/aarch64/simulator-aarch64.cc
- src/aarch64/simulator-aarch64.h
- test/aarch64/test-cpu-features-aarch64.cc
- test/aarch64/test-disasm-neon-aarch64.cc
- test/aarch64/test-simulator-sve-aarch64.cc
Add support for four Neon SHA-2 accelerating instructions.
> Support SHA-2 accelerating instructions

- src/pool-manager-impl.h
C++20's DR 2237 forbids using template-ids in constructors and destructors, and GCC 14 started warning about this.
> fix: avoid template-id-cdtor warning with GCC 14

- src/aarch64/logic-aarch64.cc
- src/aarch64/simulator-aarch64.cc
- src/aarch64/simulator-aarch64.h
I'm somewhat hoping to get the simulator building on Windows, this requires some POSIX interfaces to be replaced/removed.
I opted to work on replacing the various `*rand48()` functions.
As per https://linux.die.net/man/3/jrand48, these functions implement the linear congruential formula and provide the values I've used for the `std::linear_congruential_engine` template args.
It's not an exact replacement, as `*rand48` returns the upper 32-bits, while the std implementation returns the full 48bit number.
This has been accounted for in `GenerateRandomTag()`, but other locations have been left unadjusted.
> Replace rand48 with std::linear_congruential_engine in simulator

- src/aarch64/cpu-features-auditor-aarch64.h
- src/aarch64/debugger-aarch64.cc
- src/aarch64/debugger-aarch64.h
- src/aarch64/logic-aarch64.cc
- src/aarch64/pointer-auth-aarch64.cc
- src/aarch64/simulator-aarch64.cc
- src/aarch64/simulator-aarch64.h
- src/utils-vixl.h
Use `MemoryBarrier()` in place of `__sync_synchronize()` on MSVC
I had opted against using `std::atomic_thread_fence` due to the following note on [cppreference.com](https://en.cppreference.com/w/cpp/atomic/atomic_thread_fence) "Note however, that at least one atomic operation is required to set up the synchronization", yet our reads/writes seem to be done via `memcpy`.
While this [Stack overflow answer](https://stackoverflow.com/a/75773044/9109981) suggests the lack of `std::atomic` usage won't make a difference, I've opted to play it safe.
If desired, I can instead switch this to use `std::atomic_thread_fence`
Use `VirtualQuery` in place of posix pipes on Windows.
I can instead swap with with the windows specific `_pipe`/`_read`/`_write` api if you would prefer this code to more closely …
> Fix compilation of Simulator/Debugger with MSVC

- doc/range-limits.md
Add a new document explaining the range limits of branches and literal-handling instructions for AArch32 and AArch64, and the veneering capabilities of the macro assembler.
> Document limits of branches and literal instructions

- src/aarch32/location-aarch32.h
- src/invalset-vixl.h
- test/aarch32/test-assembler-aarch32.cc
- test/test-invalset.cc
Make RawLiteral (and therefore Literal) noncopyable but movable.
This is in order to prevent one instruction from appearing to refer to two literals.
Moving is permitted as it does not cause the same problem, and can be useful to allow containers of Literal
> [aarch32] Make RawLiteral (and therefore Literal) movable

- src/aarch64/macro-assembler-aarch64.h
- test/aarch64/test-assembler-aarch64.cc
Veneers were applied to backward branches too early, using only a quarter of the range available for the branch. This was caused by confusion over the units the range function expects; it accepts an offset in instructions.
Correct this and test veneers are applied only beyond the limit of the branch range.
> Fix backward branch veneers

- src/aarch64/decoder-visitor-map-aarch64.h
- src/aarch64/instructions-aarch64.cc
- src/aarch64/instructions-aarch64.h
- src/aarch64/simulator-aarch64.cc
Some Neon instructions such as sqrdmulh only operate on H and S-sized elements. The disassembler already restricts this, so extend checks to the simulator. Additionally, reuse the new register/index extraction function in other parts of the simulator.
> Restrict some multiply instructions element sizes

- test/aarch64/test-assembler-aarch64.cc
- test/aarch64/test-utils-aarch64.cc
- test/aarch64/test-utils-aarch64.h
Most MOPS sequences implement one of options "A" or "B", with slightly different flags in each case. Some `cpy` sequences also permit either forward or backward iteration, with different register results.
This relies on a new overloaded form of `Equal64` that checks that a register matches any one of the listed reference values.
In addition, renumber registers to avoid the use of `x16` in a couple of tests, because this is a MacroAssembler scratch register and could cause issues in the future.
> Make MOPS tests tolerant of implementation options.

- src/aarch64/assembler-sve-aarch64.cc
- src/aarch64/cpu-features-auditor-aarch64.cc
- src/aarch64/disasm-aarch64.cc
- src/aarch64/disasm-aarch64.h
- src/aarch64/instructions-aarch64.cc
- src/aarch64/simulator-aarch64.cc
- src/aarch64/simulator-aarch64.h
- test/aarch64/test-cpu-features-aarch64.cc
- test/aarch64/test-disasm-sve-aarch64.cc
- test/aarch64/test-simulator-sve2-aarch64.cc
Extend the SVE PMULL instructions to support Q destination elements when the CPU feature is supported.
> [sve] Support PMULLB/T for Q destination elements

- src/aarch64/disasm-aarch64.cc
- src/aarch64/instructions-aarch64.h
Positional arguments to printf (eg. %1$s) are not allowed on Windows, so remove uses of this in the disassembler, replacing them with an extension to the existing NEONFormatDecoder class.
Patch prompted by https://github.com/Linaro/vixl/pull/122
> Remove printf positional argument requirements from disassembler

- src/aarch64/assembler-aarch64.cc
- src/aarch64/constants-aarch64.h
- src/aarch64/disasm-aarch64.cc
- src/aarch64/simulator-aarch64.cc
- src/aarch64/simulator-aarch64.h
- test/aarch64/test-assembler-aarch64.cc
- test/aarch64/test-disasm-aarch64.cc
The DC ZVA instruction allows zeroing areas of memory, typically at block sizes of 64 bytes per instance. Add support for this in all components, with tests.
> Add support for DC ZVA

- tools/lint.py
Use raw strings in lint.py to fix a Python error.
> Fix python 3.12+ error

- src/aarch64/simulator-aarch64.cc
- src/aarch64/simulator-aarch64.h
Fix format specifiers in the simulator to match the given arguments. This will also silence -Wformat warnings when building with 32 bit flags.
> Fix format specifiers in the simulator
